### ISSUE TITLE
OutputPort toString improvements

### ISSUE THREAD

**Issue by rmontagnin** [alvisespano/Legodroid#2]
Inside the `OutputPort#toString()` method, the switch cases have all missing `break`s. This means that it doesn't matter what value `this` assumes, the output will always be `Out/D` as the switch will always end up being in case D. 

https://github.com/alvisespano/Legodroid/blob/e2e9b2de93a44cb810c43db7e2f825486721592e/app/src/main/java/it/unive/dais/legodroid/lib/EV3.java#L259

Furthermore, being `OutputPort` an enum, the implementation of the `toString` method could simple be the following 

```java
@SuppressLint("DefaultLocale")
@Override
@NonNull
public String toString() {
    return String.format("Out/%s", super.toString());
}
```

**Comment by giulioz** [comment]
Thanks, ci era scappato.
