### ISSUE TITLE
Better code organization

### ISSUE THREAD

**Issue by rmontagnin** [alvisespano/Legodroid#3]
Currently, both the `lib` and the `sample` code are put inside the `app` folder. This is a really bad practice as they should be split into two different Gradle modules so that the `lib` cannot depend on `sample`.  
Having them divided into two different modules will also allow parallel builds to be run, speeding up the whole project build time. Finally, having the `lib` folder separated from the `app` one will allow the first to be built as a Jar and shipped using a remote repository.

**Comment by giulioz** [comment]
@alvisespano è necessario approfondire come gestire la build di un modulo gradle per evitare di fargli forkare il codice.

**Comment by rmontagnin** [comment]
@giulioz I can solve this issue this Friday by using [Jitpack](https://jitpack.io/docs/ANDROID/). 

P.S. Speaking english inside open source projects is better, as it allows external contributors to see the discussions and understand them.

**Comment by alvisespano** [comment]
Yes, I know. This is an open issue I will try to solve asap.

**Comment by rmontagnin** [comment]
@alvisespano Why has this been closed if it's still open?

**Comment by giulioz** [comment]
Because it was solved with commit **7425486**
