### ISSUE TITLE
Publish the lib module separately from the app module as a Maven library

### ISSUE THREAD

**Issue by rmontagnin** [alvisespano/Legodroid#4]
Now that #3 has been solved by separating the `app` and `lib` modules, it is possible to use [Jitpack](https://jitpack.io/) to publish the lib module as a Maven/Gradle library without any effort. 

By doing this, users will be able to download the library and use it inside their applications without having to clone the repo, simply using the following line inside their `build.gradle ` files:

```groovy
implementation 'com.github.alvisespano:legodroid:Tag'
```

**Comment by giulioz** [comment]
Out of scope for this project.
